<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

$config['smtp_host'] = "";
$config['smtp_user'] = "";
$config['smtp_pass'] = "";
$config['smtp_port'] = "";
$config['smtp_timeout'] = "";
$config['protocol'] = "mail";
$config['mailpath'] = "";
$config['charset'] = "utf-8";
$config['mailtype'] = "html";
$config['newline'] = "\r\n";


/* Auto generated by Settings Administration on : 2015.05.18 07:43:46 */
