<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed'); 

$modules = array(
	'searching' => 'Search',
	'sfs' => 'Sfs'
	);

$aliases = array(

	);

$disable_controller = array(
'searching',
'sfs'
	);



/* Auto generated by Modules Administration on : 2015.05.18 07:41:31 */
