<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed'); 

$modules = array(
	'ajaxform' => 'Ajaxform',
	'searching' => 'Search',
	'sfs' => 'Sfs',
	'demo' => 'Demo',
	'comments' => 'Comments'
	);

$aliases = array(

	);

$disable_controller = array(
'comments'
	);



/* Auto generated by Modules Administration on : 2015.05.17 13:00:09 */
