<?php if ( ! defined('BASEPATH')){exit('Invalid file request');}

$views = array (
  'page' => 
  array (
    'page_blog' => 'Blog',
    'page_blog_post' => 'Blog Post',
    'article_comment' => 'Comments',
    'page_contact' => 'Contact',
    'drugdb' => 'Drug Database',
    'drug_info' => 'Drug Info',
    'duplicate' => 'Duplicate',
    'exchange' => 'Exchange Portal',
    'page_home' => 'Home',
    'page_my_account' => 'My Account',
    'page' => 'Page',
    'phap' => 'Phap',
    'search' => 'Search',
    'wider-page' => 'Wider Page',
  ),
  'article' => 
  array (
    'articles/ajaxform' => 'Ajax Form',
    'articles/article_comment' => 'Comment',
  ),
);


/* Auto generated by Themes Administration on : 2015.05.17 11:47:56 */
